- hosts: ubuntu
  remote_user: azureuser
  become: yes
  tasks:
    - name: Update apt and install python3
      apt:
          pkg:
            - python3
          update_cache: true
      register: apt
    - debug: var=apt.stdout_lines
    
    - name: get welcome html 
      shell:
        cmd: wget http://welendsre.koreacentral.cloudapp.azure.com/
      register: wget
    - debug: var=wget.stdout_lines

    - name: delete html tags & get the html body text
      shell:
        cmd: cat index.html | sed -e 's/<[^>]*>//g'   | sed -e '1,11d' > text.txt
      register: cat
    - debug: var=cat.stdout_lines

    - name: deal with the body by sed
      shell:
        cmd: sed -e 's/!//' text.txt | sed -e 's/,//g' | sed -e 's/\./ /g' | sed -e 's/  / /g' | sed '/^\s*$/d' > nginxbody.txt
      register: sed
    - debug: var=sed.stdout_lines

    - name: copy python script to find out frequency word
      copy:
        src: ./frequency.py
        dest: /home/azureuser
        owner: azureuser
        group: azureuser
        mode: 755

    - name: run the python script to get the result
      shell:
        cmd: python3 frequency.py
      register: python3
    - debug: var=python3.stdout_lines

